ID=5
NAME="JYOTHISH"
DEPARTMENT="CT"
AGE=22
COLLEGE="GPTC CHELAKKAREA"




print("\t\t\t\t\t\tSTUDENT DETAILS\n\n\n","ID IS :",ID,"\nNAME IS : ",NAME,"\nDEPARTMENT IS : ",DEPARTMENT,"\nAGE IS : ",AGE,"\nCOLLEGE IS : ",COLLEGE)
